
services:
  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: development
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8002:8002'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=require
      JWT_SECRET: ${JWT_SECRET}
    command: sh -c "npm install && npm run start:dev"

volumes:
  postgres_data: